const familyQuestions = [
  { id: "f1", text: { en: "What's your favorite movie?", fr: "Quel est ton film préféré ?" } },
  { id: "f2", text: { en: "Favorite cartoon as a kid?", fr: "Dessin animé préféré d'enfance ?" } },
  { id: "f3", text: { en: "Favorite food?", fr: "Plat préféré ?" } },
  { id: "f4", text: { en: "Least favorite food?", fr: "Le plat que tu aimes le moins ?" } },
  { id: "f5", text: { en: "Favorite dessert?", fr: "Dessert préféré ?" } },
  { id: "f6", text: { en: "Favorite holiday?", fr: "Fête préférée ?" } },
  { id: "f7", text: { en: "Favorite season?", fr: "Saison préférée ?" } },
  { id: "f8", text: { en: "Morning person or night owl?", fr: "Lève-tôt ou couche-tard ?" } },
  { id: "f9", text: { en: "Favorite hobby?", fr: "Passe-temps préféré ?" } },
  { id: "f10", text: { en: "Favorite color?", fr: "Couleur préférée ?" } },
  { id: "f11", text: { en: "What animal would you be?", fr: "Quel animal serais-tu ?" } },
  { id: "f12", text: { en: "What superpower would you want?", fr: "Quel super-pouvoir aimerais-tu avoir ?" } },
  { id: "f13", text: { en: "If you had a pet dragon, what would you name it?", fr: "Si tu avais un dragon de compagnie, comment l'appellerais-tu ?" } },
  { id: "f14", text: { en: "If you lived in a cartoon world, which one?", fr: "Si tu vivais dans un monde de dessin animé, lequel ?" } },
  { id: "f15", text: { en: "What would your dream house look like?", fr: "À quoi ressemblerait la maison de tes rêves ?" } },
  { id: "f16", text: { en: "What makes you laugh every time?", fr: "Qu'est-ce qui te fait rire à chaque fois ?" } },
  { id: "f17", text: { en: "Your best quality?", fr: "Ta meilleure qualité ?" } },
  { id: "f18", text: { en: "Something you're proud of?", fr: "Une chose dont tu es fier ?" } },
  { id: "f19", text: { en: "A small thing that makes you happy?", fr: "Une petite chose qui te rend heureux ?" } },
  { id: "f20", text: { en: "Your dream job as a kid?", fr: "Ton métier de rêve quand tu étais enfant ?" } },
  { id: "f21", text: { en: "A place you want to visit?", fr: "Un endroit que tu veux visiter ?" } },
  { id: "f22", text: { en: "Your dream vacation?", fr: "Les vacances de tes rêves ?" } },
  { id: "f23", text: { en: "A skill you'd love to learn?", fr: "Une compétence que tu aimerais apprendre ?" } },
  { id: "f24", text: { en: "What would you do with a free day?", fr: "Que ferais-tu avec une journée libre ?" } },
  { id: "f25", text: { en: "A goal you have?", fr: "Un objectif que tu as ?" } },
  { id: "f26", text: { en: "Describe yourself in 3 words", fr: "Décris-toi en 3 mots" } },
  { id: "f27", text: { en: "Your life as a movie title?", fr: "Ta vie en tant que titre de film ?" } },
  { id: "f28", text: { en: "A nickname for yourself?", fr: "Un surnom pour toi-même ?" } },
  { id: "f29", text: { en: "A slogan that describes you?", fr: "Un slogan qui te décrit ?" } },
  { id: "f30", text: { en: "What is your hidden talent?", fr: "Quel est ton talent caché ?" } },
  { id: "f31", text: { en: "What is the best present you ever received?", fr: "Quel est le meilleur cadeau que tu aies jamais reçu ?" } },
  { id: "f32", text: { en: "Your favorite board game?", fr: "Ton jeu de société préféré ?" } },
  { id: "f33", text: { en: "Favorite subject in school?", fr: "Matière préférée à l'école ?" } },
  { id: "f34", text: { en: "The funniest thing that happened to you this year?", fr: "La chose la plus drôle qui te soit arrivée cette année ?" } },
  { id: "f35", text: { en: "What insect are you most afraid of?", fr: "De quel insecte as-tu le plus peur ?" } },
  { id: "f36", text: { en: "If you could invent a holiday, what would it be for?", fr: "Si tu pouvais inventer une fête, pour quoi serait-ce ?" } },
  { id: "f37", text: { en: "Your favorite thing to do on a rainy day?", fr: "Ce que tu préfères faire un jour de pluie ?" } },
  { id: "f38", text: { en: "Favorite weird combination of food?", fr: "Combinaison bizarre de nourriture préférée ?" } },
  { id: "f39", text: { en: "The best joke you know?", fr: "La meilleure blague que tu connais ?" } },
  { id: "f40", text: { en: "What is a song that always makes you dance?", fr: "Quelle chanson te fait toujours danser ?" } },
  // New additions
  { id: "f41", text: { en: "If you could be any fictional character for a day, who would it be?", fr: "Si tu pouvais être un personnage fictif pour une journée, qui serait-ce ?" } },
  { id: "f42", text: { en: "What is the funniest word you know?", fr: "Quel est le mot le plus drôle que tu connais ?" } },
  { id: "f43", text: { en: "If you had a magic wand, what would you do first?", fr: "Si tu avais une baguette magique, que ferais-tu en premier ?" } },
  { id: "f44", text: { en: "What is the most adventurous thing you've ever done?", fr: "Quelle est la chose la plus aventureuse que tu aies jamais faite ?" } },
  { id: "f45", text: { en: "If you could only eat one food for a month, what would it be?", fr: "Si tu ne pouvais manger qu'un aliment pendant un mois, lequel serait-ce ?" } },
  { id: "f46", text: { en: "What is your favorite type of weather?", fr: "Quel est ton type de météo préféré ?" } },
  { id: "f47", text: { en: "What is the best gift you ever gave someone?", fr: "Quel est le meilleur cadeau que tu aies jamais offert ?" } },
  { id: "f48", text: { en: "If you could talk to any animal, which would you choose?", fr: "Si tu pouvais parler à n'importe quel animal, lequel choisirais-tu ?" } },
  { id: "f49", text: { en: "What would your perfect pizza look like?", fr: "À quoi ressemblerait ta pizza parfaite ?" } },
  { id: "f50", text: { en: "What is your earliest memory?", fr: "Quel est ton premier souvenir ?" } },
  { id: "f51", text: { en: "If you could be invisible for one hour, what would you do?", fr: "Si tu pouvais être invisible pendant une heure, que ferais-tu ?" } },
  { id: "f52", text: { en: "What is the silliest thing you have ever laughed at?", fr: "Quelle est la chose la plus bête qui t'ait fait rire ?" } },
  { id: "f53", text: { en: "What is your favorite thing about this group?", fr: "Quelle est ta chose préférée dans ce groupe ?" } },
  { id: "f54", text: { en: "If you could live anywhere in the world, where would you go?", fr: "Si tu pouvais vivre n'importe où dans le monde, où irais-tu ?" } },
  { id: "f55", text: { en: "What is the most interesting place you have ever visited?", fr: "Quel est l'endroit le plus intéressant que tu aies jamais visité ?" } },
  { id: "f56", text: { en: "What would you do if you had a whole day with no responsibilities?", fr: "Que ferais-tu si tu avais une journée entière sans responsabilités ?" } },
  { id: "f57", text: { en: "What is the nicest compliment you have ever received?", fr: "Quel est le plus beau compliment que tu aies jamais reçu ?" } },
  { id: "f58", text: { en: "If you opened a shop, what would you sell?", fr: "Si tu ouvrais une boutique, que vendrais-tu ?" } },
  { id: "f59", text: { en: "What is something you want to learn how to cook?", fr: "Qu'est-ce que tu veux apprendre à cuisiner ?" } },
  { id: "f60", text: { en: "What is the most random fact you know?", fr: "Quel est le fait le plus aléatoire que tu connais ?" } },
  { id: "f61", text: { en: "What sound do you absolutely love?", fr: "Quel son aimes-tu absolument ?" } },
  { id: "f62", text: { en: "What always cheers you up when you're feeling down?", fr: "Qu'est-ce qui te remonte toujours le moral quand tu te sens déprimé ?" } },
  { id: "f63", text: { en: "If you could have dinner with any person, real or fictional, who would it be?", fr: "Si tu pouvais dîner avec n'importe quelle personne, réelle ou fictive, qui serait-ce ?" } },
  { id: "f64", text: { en: "What is something you can do that most people cannot?", fr: "Qu'est-ce que tu peux faire que la plupart des gens ne peuvent pas ?" } },
  { id: "f65", text: { en: "If you could rename yourself, what name would you choose?", fr: "Si tu pouvais te renommer, quel nom choisirais-tu ?" } },
  { id: "f66", text: { en: "What is the most beautiful thing you have ever seen?", fr: "Quelle est la plus belle chose que tu aies jamais vue ?" } },
  { id: "f67", text: { en: "What is something that always makes you hungry?", fr: "Qu'est-ce qui te donne toujours faim ?" } },
  { id: "f68", text: { en: "If you could go on any adventure, what would it be?", fr: "Si tu pouvais partir à n'importe quelle aventure, laquelle serait-ce ?" } },
  { id: "f69", text: { en: "What is one thing you hope never changes?", fr: "Quelle est une chose que tu espères ne jamais voir changer ?" } },
  { id: "f70", text: { en: "If your life were a TV show, what would the theme song be?", fr: "Si ta vie était une émission de télé, quelle serait la chanson du générique ?" } },
];

module.exports = familyQuestions;

