const familyQuestions = [
  { id: "f1", text: "What's your favorite movie?" },
  { id: "f2", text: "Favorite cartoon as a kid?" },
  { id: "f3", text: "Favorite food?" },
  { id: "f4", text: "Least favorite food?" },
  { id: "f5", text: "Favorite dessert?" },
  { id: "f6", text: "Favorite holiday?" },
  { id: "f7", text: "Favorite season?" },
  { id: "f8", text: "Morning person or night owl?" },
  { id: "f9", text: "Favorite hobby?" },
  { id: "f10", text: "Favorite color?" },
  { id: "f11", text: "What animal would you be?" },
  { id: "f12", text: "What superpower would you want?" },
  { id: "f13", text: "If you had a pet dragon, what would you name it?" },
  { id: "f14", text: "If you lived in a cartoon world, which one?" },
  { id: "f15", text: "What would your dream house look like?" },
  { id: "f16", text: "What makes you laugh every time?" },
  { id: "f17", text: "Your best quality?" },
  { id: "f18", text: "Something you're proud of?" },
  { id: "f19", text: "A small thing that makes you happy?" },
  { id: "f20", text: "Your dream job as a kid?" },
  { id: "f21", text: "A place you want to visit?" },
  { id: "f22", text: "Your dream vacation?" },
  { id: "f23", text: "A skill you'd love to learn?" },
  { id: "f24", text: "What would you do with a free day?" },
  { id: "f25", text: "A goal you have?" },
  { id: "f26", text: "Describe yourself in 3 words" },
  { id: "f27", text: "Your life as a movie title?" },
  { id: "f28", text: "A nickname for yourself?" },
  { id: "f29", text: "A slogan that describes you?" },
  { id: "f30", text: "What is your hidden talent?" },
  { id: "f31", text: "What is the best present you ever received?" },
  { id: "f32", text: "Your favorite board game?" },
  { id: "f33", text: "Favorite subject in school?" },
  { id: "f34", text: "The funniest thing that happened to you this year?" },
  { id: "f35", text: "What insect are you most afraid of?" },
  { id: "f36", text: "If you could invent a holiday, what would it be for?" },
  { id: "f37", text: "Your favorite thing to do on a rainy day?" },
  { id: "f38", text: "Favorite weird combination of food?" },
  { id: "f39", text: "The best joke you know?" },
  { id: "f40", text: "What is a song that always makes you dance?" }
];

module.exports = familyQuestions;
