const familyQuestions = [
  { id: "f1", text: { en: "What's your favorite movie?", fr: "Quel est ton film préféré ?" } },
  { id: "f2", text: { en: "Favorite cartoon as a kid?", fr: "Dessin animé préféré d'enfance ?" } },
  { id: "f3", text: { en: "Favorite food?", fr: "Plat préféré ?" } },
  { id: "f4", text: { en: "Least favorite food?", fr: "Le plat que tu aimes le moins ?" } },
  { id: "f5", text: { en: "Favorite dessert?", fr: "Dessert préféré ?" } },
  { id: "f6", text: { en: "Favorite holiday?", fr: "Fête préférée ?" } },
  { id: "f7", text: { en: "Favorite season?", fr: "Saison préférée ?" } },
  { id: "f8", text: { en: "Morning person or night owl?", fr: "Lève-tôt ou couche-tard ?" } },
  { id: "f9", text: { en: "Favorite hobby?", fr: "Passe-temps préféré ?" } },
  { id: "f10", text: { en: "Favorite color?", fr: "Couleur préférée ?" } },
  { id: "f11", text: { en: "What animal would you be?", fr: "Quel animal serais-tu ?" } },
  { id: "f12", text: { en: "What superpower would you want?", fr: "Quel super-pouvoir aimerais-tu avoir ?" } },
  { id: "f13", text: { en: "If you had a pet dragon, what would you name it?", fr: "Si tu avais un dragon de compagnie, comment l'appellerais-tu ?" } },
  { id: "f14", text: { en: "If you lived in a cartoon world, which one?", fr: "Si tu vivais dans un monde de dessin animé, lequel ?" } },
  { id: "f15", text: { en: "What would your dream house look like?", fr: "À quoi ressemblerait la maison de tes rêves ?" } },
  { id: "f16", text: { en: "What makes you laugh every time?", fr: "Qu'est-ce qui te fait rire à chaque fois ?" } },
  { id: "f17", text: { en: "Your best quality?", fr: "Ta meilleure qualité ?" } },
  { id: "f18", text: { en: "Something you're proud of?", fr: "Une chose dont tu es fier ?" } },
  { id: "f19", text: { en: "A small thing that makes you happy?", fr: "Une petite chose qui te rend heureux ?" } },
  { id: "f20", text: { en: "Your dream job as a kid?", fr: "Ton métier de rêve quand tu étais enfant ?" } },
  { id: "f21", text: { en: "A place you want to visit?", fr: "Un endroit que tu veux visiter ?" } },
  { id: "f22", text: { en: "Your dream vacation?", fr: "Les vacances de tes rêves ?" } },
  { id: "f23", text: { en: "A skill you'd love to learn?", fr: "Une compétence que tu aimerais apprendre ?" } },
  { id: "f24", text: { en: "What would you do with a free day?", fr: "Que ferais-tu avec une journée libre ?" } },
  { id: "f25", text: { en: "A goal you have?", fr: "Un objectif que tu as ?" } },
  { id: "f26", text: { en: "Describe yourself in 3 words", fr: "Décris-toi en 3 mots" } },
  { id: "f27", text: { en: "Your life as a movie title?", fr: "Ta vie en tant que titre de film ?" } },
  { id: "f28", text: { en: "A nickname for yourself?", fr: "Un surnom pour toi-même ?" } },
  { id: "f29", text: { en: "A slogan that describes you?", fr: "Un slogan qui te décrit ?" } },
  { id: "f30", text: { en: "What is your hidden talent?", fr: "Quel est ton talent caché ?" } },
  { id: "f31", text: { en: "What is the best present you ever received?", fr: "Quel est le meilleur cadeau que tu aies jamais reçu ?" } },
  { id: "f32", text: { en: "Your favorite board game?", fr: "Ton jeu de société préféré ?" } },
  { id: "f33", text: { en: "Favorite subject in school?", fr: "Matière préférée à l'école ?" } },
  { id: "f34", text: { en: "The funniest thing that happened to you this year?", fr: "La chose la plus drôle qui te soit arrivée cette année ?" } },
  { id: "f35", text: { en: "What insect are you most afraid of?", fr: "De quel insecte as-tu le plus peur ?" } },
  { id: "f36", text: { en: "If you could invent a holiday, what would it be for?", fr: "Si tu pouvais inventer une fête, pour quoi serait-ce ?" } },
  { id: "f37", text: { en: "Your favorite thing to do on a rainy day?", fr: "Ce que tu préfères faire un jour de pluie ?" } },
  { id: "f38", text: { en: "Favorite weird combination of food?", fr: "Combinaison bizarre de nourriture préférée ?" } },
  { id: "f39", text: { en: "The best joke you know?", fr: "La meilleure blague que tu connais ?" } },
  { id: "f40", text: { en: "What is a song that always makes you dance?", fr: "Quelle chanson te fait toujours danser ?" } }
];

module.exports = familyQuestions;
