const friendsQuestions = [
  { id: "fr1", text: "Favorite movie?" },
  { id: "fr2", text: "A movie you pretend to like?" },
  { id: "fr3", text: "A song you overplayed?" },
  { id: "fr4", text: "Your guilty pleasure show?" },
  { id: "fr5", text: "Food you secretly love but shouldn't?" },
  { id: "fr6", text: "Your worst habit?" },
  { id: "fr7", text: "Your biggest red flag?" },
  { id: "fr8", text: "Something embarrassing you've done?" },
  { id: "fr9", text: "A fear you don't admit?" },
  { id: "fr10", text: "Your toxic trait?" },
  { id: "fr11", text: "Your best date?" },
  { id: "fr12", text: "Your worst date?" },
  { id: "fr13", text: "Biggest turn-off?" },
  { id: "fr14", text: "Biggest green flag?" },
  { id: "fr15", text: "Your 'type'?" },
  { id: "fr16", text: "Your celebrity crush?" },
  { id: "fr17", text: "A secret crush?" },
  { id: "fr18", text: "A bold thing you've done?" },
  { id: "fr19", text: "Something that gives you 'the ick'?" },
  { id: "fr20", text: "A weird turn-on?" },
  { id: "fr21", text: "A disgusting thing you can't stand?" },
  { id: "fr22", text: "A weird food combo you like?" },
  { id: "fr23", text: "An awkward moment you remember?" },
  { id: "fr24", text: "A strange habit you have?" },
  { id: "fr25", text: "What answer would people expect from you?" },
  { id: "fr26", text: "What's something that sounds like you but isn't?" },
  { id: "fr27", text: "What would confuse everyone if you answered it?" },
  { id: "fr28", text: "What would someone else in the group say?" },
  { id: "fr29", text: "Write an answer pretending to be another player" },
  { id: "fr30", text: "Describe your life as a drama title" },
  { id: "fr31", text: "Your personality in one sentence" },
  { id: "fr32", text: "Invent a fake job for yourself" },
  { id: "fr33", text: "What would your autobiography be called?" },
  { id: "fr34", text: "What lie do you tell most often?" },
  { id: "fr35", text: "What's the worst fashion trend you participated in?" },
  { id: "fr36", text: "What is your most irrational pet peeve?" },
  { id: "fr37", text: "The worst advice you've ever given?" },
  { id: "fr38", text: "If you were to get arrested, what would it be for?" },
  { id: "fr39", text: "What is the weirdest thing you've bought online?" },
  { id: "fr40", text: "A conspiracy theory you kind of believe in?" }
];

module.exports = friendsQuestions;
