const friendsQuestions = [
  { id: "fr1", text: { en: "Favorite movie?", fr: "Film préféré ?" } },
  { id: "fr2", text: { en: "A movie you pretend to like?", fr: "Un film que tu fais semblant d'aimer ?" } },
  { id: "fr3", text: { en: "A song you overplayed?", fr: "Une chanson que tu as trop écoutée ?" } },
  { id: "fr4", text: { en: "Your guilty pleasure show?", fr: "Ton émission inavouable ?" } },
  { id: "fr5", text: { en: "Food you secretly love but shouldn't?", fr: "Nourriture que tu adores secrètement mais que tu ne devrais pas ?" } },
  { id: "fr6", text: { en: "Your worst habit?", fr: "Ta pire habitude ?" } },
  { id: "fr7", text: { en: "Your biggest red flag?", fr: "Ton plus grand red flag ?" } },
  { id: "fr8", text: { en: "Something embarrassing you've done?", fr: "Quelque chose de gênant que tu as fait ?" } },
  { id: "fr9", text: { en: "A fear you don't admit?", fr: "Une peur que tu n'avoues pas ?" } },
  { id: "fr10", text: { en: "Your toxic trait?", fr: "Ton trait toxique ?" } },
  { id: "fr11", text: { en: "Your best date?", fr: "Ton meilleur rendez-vous ?" } },
  { id: "fr12", text: { en: "Your worst date?", fr: "Ton pire rendez-vous ?" } },
  { id: "fr13", text: { en: "Biggest turn-off?", fr: "Le plus grand tue-l'amour ?" } },
  { id: "fr14", text: { en: "Biggest green flag?", fr: "Le plus grand green flag ?" } },
  { id: "fr15", text: { en: "Your 'type'?", fr: "Ton 'genre' ?" } },
  { id: "fr16", text: { en: "Your celebrity crush?", fr: "Ton crush célèbre ?" } },
  { id: "fr17", text: { en: "A secret crush?", fr: "Un crush secret ?" } },
  { id: "fr18", text: { en: "A bold thing you've done?", fr: "Une chose audacieuse que tu as faite ?" } },
  { id: "fr19", text: { en: "Something that gives you 'the ick'?", fr: "Quelque chose qui te donne un blocage ('the ick') ?" } },
  { id: "fr20", text: { en: "A weird turn-on?", fr: "Une chose bizarre qui t'attire ?" } },
  { id: "fr21", text: { en: "A disgusting thing you can't stand?", fr: "Une chose dégoûtante que tu ne supportes pas ?" } },
  { id: "fr22", text: { en: "A weird food combo you like?", fr: "Une combinaison bizarre de nourriture que tu aimes ?" } },
  { id: "fr23", text: { en: "An awkward moment you remember?", fr: "Un moment gênant dont tu te souviens ?" } },
  { id: "fr24", text: { en: "A strange habit you have?", fr: "Une habitude étrange que tu as ?" } },
  { id: "fr25", text: { en: "What answer would people expect from you?", fr: "Quelle réponse les gens attendraient-ils de toi ?" } },
  { id: "fr26", text: { en: "What's something that sounds like you but isn't?", fr: "Qu'est-ce qui te ressemble mais n'est pas toi ?" } },
  { id: "fr27", text: { en: "What would confuse everyone if you answered it?", fr: "Qu'est-ce qui rendrait tout le monde confus si tu répondais ?" } },
  { id: "fr28", text: { en: "What would someone else in the group say?", fr: "Que dirait quelqu'un d'autre dans le groupe ?" } },
  { id: "fr29", text: { en: "Write an answer pretending to be another player", fr: "Écris une réponse en prétendant être un autre joueur" } },
  { id: "fr30", text: { en: "Describe your life as a drama title", fr: "Décris ta vie comme un titre de drame" } },
  { id: "fr31", text: { en: "Your personality in one sentence", fr: "Ta personnalité en une phrase" } },
  { id: "fr32", text: { en: "Invent a fake job for yourself", fr: "Invente-toi un faux métier" } },
  { id: "fr33", text: { en: "What would your autobiography be called?", fr: "Comment s'appellerait ton autobiographie ?" } },
  { id: "fr34", text: { en: "What lie do you tell most often?", fr: "Quel mensonge dis-tu le plus souvent ?" } },
  { id: "fr35", text: { en: "What's the worst fashion trend you participated in?", fr: "Quelle est la pire tendance mode à laquelle tu as participé ?" } },
  { id: "fr36", text: { en: "What is your most irrational pet peeve?", fr: "Quelle est ton irritation la plus irrationnelle ?" } },
  { id: "fr37", text: { en: "The worst advice you've ever given?", fr: "Le pire conseil que tu aies jamais donné ?" } },
  { id: "fr38", text: { en: "If you were to get arrested, what would it be for?", fr: "Si tu devais être arrêté, pour quoi ce serait ?" } },
  { id: "fr39", text: { en: "What is the weirdest thing you've bought online?", fr: "Quelle est la chose la plus bizarre que tu aies achetée en ligne ?" } },
  { id: "fr40", text: { en: "A conspiracy theory you kind of believe in?", fr: "Une théorie du complot à laquelle tu crois un peu ?" } },
  // New additions
  { id: "fr41", text: { en: "Something you've done that you'd never tell your parents?", fr: "Quelque chose que tu as fait que tu ne dirais jamais à tes parents ?" } },
  { id: "fr42", text: { en: "Your most unhinged 3am thought?", fr: "Ta pensée la plus folle à 3h du matin ?" } },
  { id: "fr43", text: { en: "A hill you would absolutely die on?", fr: "Une opinion que tu défendrais coûte que coûte ?" } },
  { id: "fr44", text: { en: "What is your most embarrassing childhood memory?", fr: "Quel est ton souvenir d'enfance le plus embarrassant ?" } },
  { id: "fr45", text: { en: "What is your most controversial opinion?", fr: "Quelle est ton opinion la plus controversée ?" } },
  { id: "fr46", text: { en: "What is the dumbest thing you've ever argued about?", fr: "Sur quoi as-tu eu la dispute la plus stupide ?" } },
  { id: "fr47", text: { en: "What is a totally irrational thing you still believe?", fr: "Quelle est une chose totalement irrationnelle à laquelle tu crois encore ?" } },
  { id: "fr48", text: { en: "What do you pretend not to care about but actually do?", fr: "À quoi fais-tu semblant d'être indifférent mais tu ne l'es pas ?" } },
  { id: "fr49", text: { en: "What is the most dramatic thing you've ever done?", fr: "Quelle est la chose la plus dramatique que tu aies jamais faite ?" } },
  { id: "fr50", text: { en: "What is your go-to excuse when you cancel plans?", fr: "Quelle est ton excuse habituelle quand tu annules des plans ?" } },
  { id: "fr51", text: { en: "What is something you've said that you immediately regretted?", fr: "Quelque chose que tu as dit et que tu as immédiatement regretté ?" } },
  { id: "fr52", text: { en: "What is the most impulsive thing you've done?", fr: "Quelle est la chose la plus impulsive que tu aies faite ?" } },
  { id: "fr53", text: { en: "What is something you do that you know is weird but can't stop?", fr: "Quelque chose que tu fais et sais être bizarre mais ne peux pas arrêter ?" } },
  { id: "fr54", text: { en: "What is the pettiest thing you've ever done?", fr: "Quelle est la chose la plus mesquine que tu aies jamais faite ?" } },
  { id: "fr55", text: { en: "What is a bad habit you've tried and failed to break?", fr: "Quelle mauvaise habitude as-tu essayé mais échoué à rompre ?" } },
  { id: "fr56", text: { en: "What is the most ridiculous thing you've ever spent money on?", fr: "Quelle est la chose la plus ridicule pour laquelle tu as dépensé de l'argent ?" } },
  { id: "fr57", text: { en: "What is a skill you've lied about having?", fr: "Quelle compétence as-tu prétendu avoir sans l'avoir ?" } },
  { id: "fr58", text: { en: "What is the strangest compliment you've ever received?", fr: "Quel est le compliment le plus étrange que tu aies jamais reçu ?" } },
  { id: "fr59", text: { en: "What is one thing you would change about yourself if you could?", fr: "Quelle est une chose que tu changerais en toi si tu pouvais ?" } },
  { id: "fr60", text: { en: "What would your villain name be?", fr: "Quel serait ton nom de méchant ?" } },
  { id: "fr61", text: { en: "What is the most cringe thing on your old social media?", fr: "Quelle est la chose la plus embarrassante sur tes vieux réseaux sociaux ?" } },
  { id: "fr62", text: { en: "What have you Googled that you'd be embarrassed to admit?", fr: "Qu'as-tu googé que tu aurais honte d'admettre ?" } },
  { id: "fr63", text: { en: "What is the weirdest dream you've had recently?", fr: "Quel est le rêve le plus bizarre que tu aies fait récemment ?" } },
  { id: "fr64", text: { en: "What is the worst date you could imagine going on?", fr: "Quel est le pire rendez-vous que tu puisses imaginer ?" } },
  { id: "fr65", text: { en: "What is the most embarrassing thing in your camera roll?", fr: "Quelle est la chose la plus embarrassante dans ton album photos ?" } },
  { id: "fr66", text: { en: "What is something you've done that you're not proud of but kind of are?", fr: "Quelque chose que tu as fait dont tu n'es pas fier mais un peu quand même ?" } },
  { id: "fr67", text: { en: "What is your most embarrassing fashion moment?", fr: "Quel est ton moment mode le plus embarrassant ?" } },
  { id: "fr68", text: { en: "If you could read minds for one day, whose would you read?", fr: "Si tu pouvais lire les pensées pendant un jour, qui choisirais-tu ?" } },
  { id: "fr69", text: { en: "What is the strangest conversation you've had with a stranger?", fr: "Quelle est la conversation la plus étrange que tu aies eue avec un inconnu ?" } },
  { id: "fr70", text: { en: "What is a dealbreaker in a friendship?", fr: "Qu'est-ce qui est rédhibitoire dans une amitié ?" } },
];

module.exports = friendsQuestions;

