module.exports = [
  // Funny
  "Who would accidentally go viral?",
  "Who would forget their own birthday?",
  "Who would survive the longest in the wild?",
  "Who would adopt 5 cats?",
  "Who would become a reality TV star?",
  "Who would show up 30 minutes late to their own wedding?",
  "Who would order the weirdest thing on the menu?",
  "Who would become obsessed with a niche hobby nobody else gets?",
  "Who would go on a spontaneous road trip with zero plan?",
  "Who would accidentally befriend a celebrity?",
  // Edgy
  "Who is most likely to text their ex at 3AM?",
  "Who would ghost someone after a great first date?",
  "Who would lie on a job interview?",
  "Who would wake up in a foreign country with no memory?",
  "Who would accidentally send a text to the wrong person?",
  "Who would start drama at a family dinner?",
  "Who would quit their job completely on impulse?",
  "Who would call in sick just to binge a TV show?",
  "Who would spend a whole paycheck on something ridiculous?",
  "Who would start an argument just for the fun of it?",
  // Absurd
  "Who would accidentally join a cult?",
  "Who would start a conspiracy theory that goes viral?",
  "Who would betray the group in a zombie apocalypse?",
  "Who would run for president on a completely ridiculous platform?",
  "Who would discover a hidden talent at age 80?",
  "Who would end up on a wanted poster?",
  "Who would invent something useless but oddly popular?",
  "Who would get lost in a building they've been in 100 times?",
  "Who would argue with a GPS until the very end?",
  "Who would somehow end up on the news for the strangest reason?",
  // Social
  "Who would cry at a commercial?",
  "Who would overshare on a first date?",
  "Who would be the last to know about any gossip?",
  "Who would bring a lawyer to a board game dispute?",
  "Who would apologize to furniture they bumped into?",
  "Who would befriend someone they just met at a wedding?",
  "Who would give a roast speech at the wrong moment?",
  "Who would accidentally make eye contact with someone for way too long?",
  "Who would be the first to offer unsolicited life advice?",
  "Who would narrate their own life out loud like a documentary?",
  // Skills & survival
  "Who would somehow build a working shelter with zero experience?",
  "Who would survive a zombie apocalypse using random life skills?",
  "Who would become a self-taught master chef after just one week?",
  "Who would accidentally solve a major math problem on a napkin?",
  "Who would become a professional napper?",
  "Who would cry during a job performance review?",
  "Who would accidentally break a world record?",
  "Who would become a cult following after one weird online post?",
  // Deep
  "Who would write a best-selling memoir nobody asked for?",
  "Who would write a strongly-worded letter to a company and actually get a response?",
  "Who would convince everyone around them to move cities?",
  "Who would start a commune in the woods and thrive?",
  "Who would secretly have a second career nobody knows about?",
  "Who would be the most likely to go off the grid for a year?",
  "Who would panic and propose on a third date?",
  "Who would accidentally become a local legend?",
  "Who would get banned from a board game night?",
  "Who would somehow end up hosting a kids' birthday party they knew nothing about?",
  // Personality labels
  "Who is the most dramatic in the group?",
  "Who is secretly the smartest person here?",
  "Who is the biggest control freak?",
  "Who is the most chaotically unpredictable?",
  "Who fakes it the most when meeting new people?",
  "Who has the best taste in the group?",
  "Who pretends to know more than they actually do?",
  "Who is the most emotionally unavailable?",
  "Who would be the worst boss?",
  "Who is the most trustworthy person here?",
  "Who is the most likely to keep a secret forever?",
  "Who is the group therapist nobody asked for?",
  "Who is low-key the most competitive?",
  "Who is secretly judging everyone right now?",
  "Who has the best poker face?",
  // Scenario reactions
  "Who would laugh at a funeral?",
  "Who would cry watching a movie?",
  "Who would start filming instead of helping in an emergency?",
  "Who would argue with a police officer and somehow win?",
  "Who would make it super awkward if a waiter spilled a drink on them?",
  "Who would panic first in an emergency?",
  "Who would cry during a speech?",
  "Who would flirt their way out of getting a fine?",
  "Who would forget where they parked and deny it?",
  "Who would go viral one day?",
  "Who would adopt a pet completely on impulse?",
  "Who would get canceled online?",
  "Who would get arrested in another country?",
  "Who would end up on a reality dating show?",
  "Who would be the first to give up in a group project?",
  "Who would apologize to an inanimate object they bumped into?",
];
