// Traits for Photo Association mode (photoassoc).
// Players vote on which person best fits the "most likely to..." scenario.

const photoAssocTraits = [
  'Most likely to accidentally go viral',
  'Most likely to be the main character',
  'Most likely to start a business that fails spectacularly',
  'Most likely to have a secret talent no one knows about',
  'Most likely to quote a movie at an inappropriate time',
  'Most likely to be abducted by aliens (willingly)',
  'Most likely to become a beloved local legend',
  'Most likely to argue with a robot',
  'Most likely to accidentally invent something',
  'Most likely to be described as "a lot"',
  'Most likely to survive off vibes alone',
  'Most likely to have read the terms and conditions',
  'Most likely to get into an argument with a stranger and win',
  'Most likely to start a podcast no one asked for',
  'Most likely to write a strongly worded letter',
  'Most likely to eat cereal at 2am',
  'Most likely to lose their keys every single day',
  'Most likely to be in a band secretly',
  'Most likely to have an opinion about everything',
  'Most likely to hug a tree and mean it',
  // New additions — funny
  'Most likely to befriend a pigeon',
  'Most likely to get banned from a trivia night',
  'Most likely to accidentally become a meme',
  'Most likely to adopt a raccoon as a pet',
  'Most likely to win a staring contest against a dog',
  'Most likely to turn a 5-minute errand into a 3-hour adventure',
  'Most likely to fall asleep on public transport and miss their stop',
  'Most likely to have a detailed plan for the zombie apocalypse',
  'Most likely to bring a snack to a very serious meeting',
  'Most likely to send a voice note when a text would do',
  // Absurd
  'Most likely to accidentally start a diplomatic incident',
  'Most likely to convince a crowd to do something weird',
  'Most likely to be hired as a consultant for something they made up',
  'Most likely to have a Wikipedia page by age 40',
  'Most likely to be featured on a documentary they did not know was being filmed',
  'Most likely to negotiate their way out of any situation',
  'Most likely to accidentally discover a new species',
  'Most likely to know a surprisingly useful obscure fact',
  // Social
  'Most likely to know everyone at the party',
  'Most likely to spend the whole party in the kitchen',
  'Most likely to become best friends with the waiter',
  'Most likely to bring up something completely unrelated mid-conversation',
  'Most likely to give a 10-minute speech when asked for a quick word',
  'Most likely to remember every detail of something that happened 5 years ago',
  // Skills
  'Most likely to be a terrible co-pilot',
  'Most likely to give perfect advice they never follow themselves',
  'Most likely to overcomplicate a simple task',
  'Most likely to teach themselves something random at 2am',
  'Most likely to build a very impressive-looking spreadsheet for something trivial',
  'Most likely to fix something by turning it off and on again',
  // Life choices
  'Most likely to quit their job for a gap year and love it',
  'Most likely to have an unusual but fascinating career path',
  'Most likely to move to a different country on a whim',
  'Most likely to still be awake at 4am for no reason',
  'Most likely to make a major life decision based on a horoscope',
  'Most likely to have strong opinions about a niche topic',
  'Most likely to own an unusual but adorable collection',
  'Most likely to be right about something everyone else dismissed',
  'Most likely to say "it\'s fine" right before something breaks',
  'Most likely to have the most chaotic but somehow functional life',
];

module.exports = { photoAssocTraits };
