// Situational prompts — {target} is replaced by the target player's name at runtime
module.exports = [
  "If {target} found $100 on the street, what would they do with it?",
  "What would {target} panic-Google at 2am?",
  "If {target} had to appear on a reality TV show, which one would it be?",
  "What dumb rule would {target} enforce if they ran the world for a day?",
  "If {target}'s life had a theme song, what genre would it be?",
  "What would {target} say is their biggest unpopular opinion?",
  "What would {target} do if they woke up famous overnight?",
  "What is {target} most likely to get weirdly passionate about?",
  "What would {target} order at a restaurant and then immediately regret?",
  "If {target} had to skip adulting for a week, what would they do?",
  "What skill would {target} lie about on a resume?",
  "What would {target} be the world's worst at?",
  "What would {target} do if they had one hour of total invisibility?",
  "If {target} had to choose — fame, money, or love — what do they pick?",
  "What bad habit does {target} definitely have but would never admit?",
  "What conspiracy theory would {target} totally believe?",
  "What would {target} spend a whole weekend procrastinating on?",
  "What excuse would {target} use to get out of a boring event?",
  "If {target} were a supervillain, what would their evil plan be?",
  "What random item would {target} become obsessed with collecting?",
  "If {target} could master one skill overnight, what would they pick?",
  "What hobby would {target} start and quit after two weeks?",
  "What would {target}'s reaction be if they accidentally liked a 3-year-old photo?",
  "What would {target} name their own podcast if they started one?",
  "If {target} had to survive on one meal forever, what would it be?",
  "What's the most dramatic thing {target} would ever do for free Wi-Fi?",
  "What would {target} do as the very last person alive on Earth?",
  "If {target} could rewrite one rule of society, what would it be?",
  "What talent show act would {target} enter?",
  "What would {target} accidentally start a revolution over?",
];
