// This-or-That questions — each has a prompt text and two choices: a and b
module.exports = [
  { text: "If you had to pick one forever:", a: "Coffee ☕", b: "Tea 🍵" },
  { text: "Pick your ideal weekend:", a: "Party 🎉", b: "Stay home 🛋️" },
  { text: "Which do you lean toward?", a: "Early bird 🌅", b: "Night owl 🦉" },
  { text: "You'd rather travel by:", a: "Plane ✈️", b: "Road trip 🚗" },
  { text: "Pick your movie night:", a: "Comedy 😂", b: "Horror 😱" },
  { text: "If you had to eat one forever:", a: "Pizza 🍕", b: "Tacos 🌮" },
  { text: "Your communication style:", a: "Call me 📞", b: "Text me 💬" },
  { text: "Pick your season:", a: "Summer ☀️", b: "Winter ❄️" },
  { text: "You're more of a:", a: "Planner 📅", b: "Spontaneous 🎲" },
  { text: "Which power would you pick?", a: "Fly 🦅", b: "Invisible 🫥" },
  { text: "If you had to live in one:", a: "City 🏙️", b: "Countryside 🌾" },
  { text: "Your social vibe:", a: "Extrovert 🗣️", b: "Introvert 🤫" },
  { text: "Pet preference:", a: "Dogs 🐶", b: "Cats 🐱" },
  { text: "Breakfast choice:", a: "Sweet 🥞", b: "Savoury 🍳" },
  { text: "Your style in a crisis:", a: "Stay calm 🧊", b: "Full panic 😵" },
  { text: "Pick a time machine direction:", a: "Past ⏪", b: "Future ⏩" },
  { text: "You'd rather be:", a: "Famous 🌟", b: "Rich 💰" },
  { text: "Shopping preference:", a: "Online 📦", b: "In-store 🛍️" },
  { text: "Pick your Friday night:", a: "Games night 🎮", b: "Night out 🍸" },
  { text: "Work style:", a: "Remote 🏠", b: "Office 🏢" },
  { text: "Music mood:", a: "Upbeat 🎵", b: "Chill 🎶" },
  { text: "Cooking vs eating out:", a: "Cook at home 🍳", b: "Restaurant 🍽️" },
  { text: "Your book pick:", a: "Fiction 📖", b: "Non-fiction 📚" },
  { text: "Pick a skill to master:", a: "Cooking 👨‍🍳", b: "Music 🎸" },
  { text: "Your horror movie role:", a: "Survives 🏃", b: "First to go 💀" },
  // Previous additions
  { text: "If you had to pick a pet:", a: "Parrot 🦜", b: "Turtle 🐢" },
  { text: "Your approach to a problem:", a: "Research everything 📊", b: "Wing it 🎲" },
  { text: "Holiday vibe:", a: "Beach 🏖️", b: "Mountains 🏔️" },
  { text: "Your social media:", a: "Post everything 📸", b: "Ghost 👻" },
  { text: "Pick your villain power:", a: "Mind control 🧠", b: "Time stop ⏱️" },
  { text: "Relationship style:", a: "PDA couple 💕", b: "Private couple 🤐" },
  { text: "Your weekend energy:", a: "Productive ✅", b: "Pure rest 😴" },
  { text: "If stranded on an island:", a: "Rescue signal 🆘", b: "Build a life 🌴" },
  { text: "Learning style:", a: "Hands on 🛠️", b: "Read & study 📚" },
  { text: "Gift giving preference:", a: "Thoughtful & personal 🎁", b: "Cash & gift cards 💳" },
  { text: "Your debate style:", a: "Logic & facts 📋", b: "Passion & gut 🔥" },
  { text: "Pick your power-up:", a: "Never need sleep 😴", b: "Read minds 💭" },
  { text: "Your ideal vacation:", a: "Backpacking trip 🎒", b: "Luxury resort 🍹" },
  { text: "Pick your alternate life:", a: "Rockstar 🎸", b: "Scientist 🔬" },
  { text: "Social preference:", a: "Big friend group 🎉", b: "Small tight circle 💎" },
  { text: "Career dream:", a: "Work for yourself 🏠", b: "Big company career 🏢" },
  { text: "Your approach to conflict:", a: "Address it head-on 🥊", b: "Avoid & move on 🕊️" },
  { text: "Rainy day plan:", a: "Movie marathon 🎬", b: "Board games 🎲" },
  { text: "Dining style:", a: "Try somewhere new 🗺️", b: "Return to favs ❤️" },
  { text: "Your pace in life:", a: "Hustle & chase goals 🚀", b: "Slow & enjoy the ride 🌊" },
  { text: "Party role:", a: "The entertainer 🎤", b: "The wallflower observer 👀" },
  // New additions
  { text: "Pick your superpower:", a: "Teleportation 🌀", b: "Time travel ⌛" },
  { text: "Your ideal house:", a: "Cosy cottage 🏡", b: "Modern penthouse 🏙️" },
  { text: "Which would ruin your day more?", a: "No phone all day 📵", b: "No food all day 🍽️" },
  { text: "Pick your chaos agent:", a: "Impulse buyer 🛒", b: "Spontaneous traveller ✈️" },
  { text: "Your sport:", a: "Team sport 🏀", b: "Solo sport 🎾" },
  { text: "Preferred storytelling:", a: "Exaggerate wildly 📢", b: "Just the facts 🧾" },
  { text: "Morning routine:", a: "Alarm snooze champion ⏰", b: "Up before the alarm ☀️" },
  { text: "Your drink at 11pm:", a: "Hot chocolate 🍫", b: "Energy drink ⚡" },
  { text: "Pick your chaos:", a: "Overshare online 📲", b: "Complete digital ghost 👻" },
  { text: "Your relationship with plans:", a: "Over-planner with backup plans 📝", b: "Plans are suggestions 🤷" },
  { text: "Which would you choose?", a: "Know when you'll die 💀", b: "Know everyone's true feelings 💭" },
  { text: "Karaoke style:", a: "Full performance, mic drop 🎤", b: "Only if literally forced 😬" },
  { text: "Airport type:", a: "3 hours early, ready 🏃", b: "Last-minute sprint ⏱️" },
  { text: "Pick your life philosophy:", a: "Live for today 🌅", b: "Plan for tomorrow 📅" },
  { text: "Your true calling:", a: "Creative career 🎨", b: "Analytical career 🧮" },
  { text: "Your Netflix habit:", a: "One episode at a time 🧘", b: "Entire season in one night 📺" },
  { text: "Honesty policy:", a: "Brutal honesty always 🔪", b: "White lies to protect feelings 🤍" },
  { text: "Pick your legacy:", a: "Remembered for great work 🏆", b: "Remembered for great laughs 😂" },
  { text: "Your ideal date:", a: "Cosy dinner in 🕯️", b: "Wild adventure out 🌋" },
  { text: "If you had to pick a language to learn:", a: "Mandarin 🀄", b: "Sign language 🤟" },
  { text: "Nightmare scenario:", a: "Public speaking to 1,000 people 🎙️", b: "Trapped in an escape room alone 🔐" },
  { text: "Your energy at events:", a: "First to arrive, last to leave 🥳", b: "Fashionably late, early exit 🕶️" },
  { text: "Choose your downfall:", a: "Overconfidence 💪", b: "Overthinking 🌀" },
  { text: "Type of risk you prefer:", a: "Financial risk 💸", b: "Social risk 👥" },
  { text: "Your coping mechanism:", a: "Talk it out 🗣️", b: "Go quiet and process alone 🤐" },
];

